#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <locale.h>
#include "modulocliente.h"
//char cadastro_usuario(void);
//har lista_usuario(void);
//char apagar_usuario(void);
//char editar_usuario(void);