void menu_nav_veiculo(void);
char menu_veiculo(void);
void menu_cadastro_veiculo(void);
char menu_lista_veiculo(void);
void menu_apagar_veiculo(void);
char menu_editar_veiculo(void);
void menu_veiculo_manutencao(void);
char menu_lista_agendamento(void);
void menu_cadastro_veiculo(void);