void menu_nav_adm(void);
char menu_gastos_da_empresa(void);
char menu_fluxo_caixa(void);
char menu_adm(void);
char menu_relatorios(void);
void nav_relatorio_cliente(void);
void R_lista_cliente(void);
void nav_relatorio_veiculo(void);
void R_lista_veiculo(void);
